language: node_js

node_js:
  - "node"

cache: yarn

branches:
  only:
    - master

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: public
  target-branch: gh-pages
  on:
    branch: master
